
version: '3'

services: 
    api:
        build: './api'
        ports: 
            - "3000:3000"
        network_mode: host
        depends_on:
          - elasticspring
    
    elasticspring:
        build: './elastic'
        ports:
            - "8080:8080"
        network_mode: host

